package com.david.llegeix.data.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * Adds pinning, bookmarking, colours and read-later.
 *
 * Written out rather than falling back to destructive migration: folders and
 * bookmarks are hand-made by the user and cannot be regenerated by rescanning,
 * unlike the document rows themselves.
 */
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE folders ADD COLUMN isPinned INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE folders ADD COLUMN isBookmarked INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE folders ADD COLUMN colorArgb INTEGER")
        db.execSQL("ALTER TABLE documents ADD COLUMN isBookmarked INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE documents ADD COLUMN isReadLater INTEGER NOT NULL DEFAULT 0")
    }
}

/**
 * Adds saved words.
 *
 * The table mirrors [com.david.llegeix.data.db.entity.WordBookmarkEntity]: the
 * document reference is nullable and set to null rather than cascading, so a
 * word survives the PDF it came from being forgotten.
 */
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `word_bookmarks` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `word` TEXT NOT NULL,
                `translation` TEXT,
                `ipa` TEXT,
                `context` TEXT,
                `documentUri` TEXT,
                `displayName` TEXT,
                `pageIndex` INTEGER NOT NULL,
                `lineNumber` INTEGER NOT NULL,
                `createdAt` INTEGER NOT NULL,
                FOREIGN KEY(`documentUri`) REFERENCES `documents`(`uriString`)
                    ON UPDATE NO ACTION ON DELETE SET NULL
            )
            """.trimIndent(),
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_word_bookmarks_documentUri` " +
                "ON `word_bookmarks` (`documentUri`)",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_word_bookmarks_word` " +
                "ON `word_bookmarks` (`word`)",
        )
    }
}

/**
 * Adds tags.
 *
 * Two tables: the tags themselves, and the pairings. Both cascade on delete, so
 * removing a document or a tag cleans up its links rather than leaving rows
 * pointing at nothing.
 */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `tags` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `name` TEXT NOT NULL,
                `colorArgb` INTEGER NOT NULL,
                `createdAt` INTEGER NOT NULL
            )
            """.trimIndent(),
        )
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_tags_name` ON `tags` (`name`)")
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `document_tags` (
                `documentUri` TEXT NOT NULL,
                `tagId` INTEGER NOT NULL,
                PRIMARY KEY(`documentUri`, `tagId`),
                FOREIGN KEY(`documentUri`) REFERENCES `documents`(`uriString`)
                    ON UPDATE NO ACTION ON DELETE CASCADE,
                FOREIGN KEY(`tagId`) REFERENCES `tags`(`id`)
                    ON UPDATE NO ACTION ON DELETE CASCADE
            )
            """.trimIndent(),
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_document_tags_tagId` " +
                "ON `document_tags` (`tagId`)",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_document_tags_documentUri` " +
                "ON `document_tags` (`documentUri`)",
        )
    }
}

/**
 * Adds the per-folder decisions behind the sources screen.
 *
 * Nothing is inserted: an empty table means every folder inside every granted
 * source is shown, which is exactly how the app behaved before this table
 * existed.
 */
val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `folder_rules` (
                `path` TEXT NOT NULL,
                `included` INTEGER NOT NULL,
                PRIMARY KEY(`path`)
            )
            """.trimIndent(),
        )
    }
}

/**
 * Keeps what a saved word meant in the line it was saved from.
 *
 * All three columns are nullable with no default, which is what makes this
 * safe: a word saved before v3.1 simply has no contextual reading, and the
 * screen already draws each of these only when it is there. Nothing is
 * back-filled, because the reading cannot be recomputed without the translator
 * and the page, and a guessed one would be worse than none.
 */
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN contextTranslation TEXT")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN senseTranslation TEXT")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN senseSource TEXT")
    }
}

/**
 * Records how long a document is, so the app can say how far through it you are.
 *
 * Nullable with no default rather than a zero: "not opened yet" and "a document
 * of no pages" are different facts, and only the first is true of every row
 * that exists when this runs. Nothing is back-filled — the count comes from
 * opening the file, and opening every PDF the library has ever seen in a
 * migration would block the first launch after an update for as long as the
 * reader's library is large.
 */
val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE documents ADD COLUMN pageCount INTEGER")
    }
}

/**
 * Gives every saved word a place in the practice deck.
 *
 * The three columns have defaults rather than being nullable, because unlike
 * the columns added in 5→6 there is a right answer for a word saved before this
 * existed: box zero, due now, never reviewed. A vocabulary list that has been
 * building for months should arrive in the new deck as a deck, not as a hundred
 * rows the scheduler has to be taught to ignore.
 */
val MIGRATION_7_8 = object : Migration(7, 8) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN box INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN dueAt INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN reviewCount INTEGER NOT NULL DEFAULT 0")
    }
}

/**
 * Makes room for exams: the paper, the sittings, and the recordings.
 *
 * Three new tables and not one column touched on the existing eight, because an
 * exam is not a document in the library sense. A document is a `content://` URI
 * the app was granted a look at; an exam is a file the app has copied and now
 * owns outright, and the two have different lifetimes, different deletion rules
 * and different privacy consequences. Filing exams in `documents` would have
 * meant every query about the reader's library quietly returning exam papers.
 *
 * The foreign keys carry ON DELETE CASCADE, so deleting a paper takes its
 * sittings and its audio rows with it. The *files* those rows name are deleted
 * by [com.david.llegeix.data.exam.ExamRepository], which reads the names first;
 * SQLite cannot unlink anything.
 */
val MIGRATION_8_9 = object : Migration(8, 9) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exams` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `title` TEXT NOT NULL, `sourceName` TEXT NOT NULL, `fileName` TEXT NOT NULL, `pageCount` INTEGER NOT NULL, `answerKeyFileName` TEXT, `answerKeyPageCount` INTEGER, `createdAt` INTEGER NOT NULL)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_attempts` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `examId` INTEGER NOT NULL, `label` TEXT NOT NULL, `startedAt` INTEGER NOT NULL, `lastOpenedAt` INTEGER NOT NULL, `finishedAt` INTEGER, `lastPage` INTEGER NOT NULL, FOREIGN KEY(`examId`) REFERENCES `exams`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_attempts_examId` ON `exam_attempts` (`examId`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_audio` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `examId` INTEGER NOT NULL, `displayName` TEXT NOT NULL, `fileName` TEXT NOT NULL, `durationMs` INTEGER, `position` INTEGER NOT NULL, FOREIGN KEY(`examId`) REFERENCES `exams`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_audio_examId` ON `exam_audio` (`examId`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_marks` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `attemptId` INTEGER NOT NULL, `pageIndex` INTEGER NOT NULL, `kind` TEXT NOT NULL, `x` REAL NOT NULL, `y` REAL NOT NULL, `width` REAL NOT NULL, `height` REAL NOT NULL, `colorArgb` INTEGER NOT NULL, `size` REAL NOT NULL, `text` TEXT, `points` TEXT, `checked` INTEGER NOT NULL, `sequence` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, FOREIGN KEY(`attemptId`) REFERENCES `exam_attempts`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_marks_attemptId_pageIndex` ON `exam_marks` (`attemptId`, `pageIndex`)",
        )
    }
}

/**
 * An exam becomes a paper made of documents.
 *
 * A Catalan exam sample routinely arrives as several PDFs — the reading, the
 * listening, the writing — which are one exam to the person sitting them and
 * were three unrelated rows in this app. [ExamPartEntity] is where the documents
 * go, in order, and [ExamEntity] keeps only the identity of the paper.
 *
 * ### Why this is written the long way round
 *
 * Removing three columns from `exams` means recreating the table, and `exams`
 * is a parent whose children cascade on delete. With foreign keys enabled —
 * which is how the app runs — `DROP TABLE exams` performs an implicit
 * `DELETE FROM exams` first, and that fires ON DELETE CASCADE on every attempt,
 * every recording and, through the attempts, every mark. `PRAGMA
 * defer_foreign_keys` does not prevent it: deferral changes when a violation is
 * reported, not whether a cascade runs. The obvious three-line migration would
 * therefore delete every answer the reader has ever written, silently, on
 * upgrade, and leave a perfectly valid-looking database behind.
 *
 * So the children are copied into staging tables that carry no foreign keys at
 * all, dropped, and rebuilt afterwards. `exams` is only recreated once nothing
 * references it, at which point its implicit delete has nothing to cascade to.
 *
 * This was verified against a populated v9 database with foreign keys on before
 * it was written here: every row survives, every mark lands on the part
 * belonging to its own attempt's exam, and `PRAGMA foreign_key_check` comes back
 * clean.
 */
val MIGRATION_9_10 = object : Migration(9, 10) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // 1. Stage every child's rows somewhere no cascade can reach them. The
        //    staging tables deliberately declare no foreign keys.
        db.execSQL(
            """
            CREATE TABLE _m_parts (
                examId INTEGER NOT NULL, sourceName TEXT NOT NULL, fileName TEXT NOT NULL,
                pageCount INTEGER NOT NULL, position INTEGER NOT NULL
            )
            """.trimIndent(),
        )
        // The one document each exam already had becomes its first part.
        db.execSQL(
            """
            INSERT INTO _m_parts (examId, sourceName, fileName, pageCount, position)
            SELECT id, sourceName, fileName, pageCount, 0 FROM exams
            """.trimIndent(),
        )
        db.execSQL("CREATE TABLE _m_attempts AS SELECT * FROM exam_attempts")
        db.execSQL("CREATE TABLE _m_audio AS SELECT * FROM exam_audio")
        db.execSQL("CREATE TABLE _m_marks AS SELECT * FROM exam_marks")

        // 2. Drop the children. Dropping a child cascades to nothing.
        db.execSQL("DROP TABLE exam_marks")
        db.execSQL("DROP TABLE exam_audio")
        db.execSQL("DROP TABLE exam_attempts")

        // 3. Only now recreate exams, with nothing left pointing at it.
        db.execSQL(
            """
            CREATE TABLE exams_new (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `title` TEXT NOT NULL,
                `answerKeyFileName` TEXT, `answerKeyPageCount` INTEGER,
                `createdAt` INTEGER NOT NULL
            )
            """.trimIndent(),
        )
        db.execSQL(
            """
            INSERT INTO exams_new (id, title, answerKeyFileName, answerKeyPageCount, createdAt)
            SELECT id, title, answerKeyFileName, answerKeyPageCount, createdAt FROM exams
            """.trimIndent(),
        )
        db.execSQL("DROP TABLE exams")
        db.execSQL("ALTER TABLE exams_new RENAME TO exams")

        // 4. Rebuild the children in their v10 shape.
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_parts` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `examId` INTEGER NOT NULL, `sourceName` TEXT NOT NULL, `fileName` TEXT NOT NULL, `pageCount` INTEGER NOT NULL, `position` INTEGER NOT NULL, FOREIGN KEY(`examId`) REFERENCES `exams`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_parts_examId` ON `exam_parts` (`examId`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_attempts` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `examId` INTEGER NOT NULL, `label` TEXT NOT NULL, `startedAt` INTEGER NOT NULL, `lastOpenedAt` INTEGER NOT NULL, `finishedAt` INTEGER, `lastPage` INTEGER NOT NULL, FOREIGN KEY(`examId`) REFERENCES `exams`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_attempts_examId` ON `exam_attempts` (`examId`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_audio` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `examId` INTEGER NOT NULL, `displayName` TEXT NOT NULL, `fileName` TEXT NOT NULL, `durationMs` INTEGER, `position` INTEGER NOT NULL, FOREIGN KEY(`examId`) REFERENCES `exams`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_audio_examId` ON `exam_audio` (`examId`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `exam_marks` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `attemptId` INTEGER NOT NULL, `partId` INTEGER NOT NULL, `pageIndex` INTEGER NOT NULL, `kind` TEXT NOT NULL, `x` REAL NOT NULL, `y` REAL NOT NULL, `width` REAL NOT NULL, `height` REAL NOT NULL, `colorArgb` INTEGER NOT NULL, `size` REAL NOT NULL, `text` TEXT, `points` TEXT, `checked` INTEGER NOT NULL, `sequence` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, FOREIGN KEY(`attemptId`) REFERENCES `exam_attempts`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE , FOREIGN KEY(`partId`) REFERENCES `exam_parts`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_marks_attemptId_partId_pageIndex` ON `exam_marks` (`attemptId`, `partId`, `pageIndex`)",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_exam_marks_partId` ON `exam_marks` (`partId`)",
        )

        // 5. Refill them, and give every mark the part it was really made on.
        db.execSQL(
            """
            INSERT INTO exam_parts (examId, sourceName, fileName, pageCount, position)
            SELECT examId, sourceName, fileName, pageCount, position FROM _m_parts
            """.trimIndent(),
        )
        db.execSQL(
            """
            INSERT INTO exam_attempts
                (id, examId, label, startedAt, lastOpenedAt, finishedAt, lastPage)
            SELECT id, examId, label, startedAt, lastOpenedAt, finishedAt, lastPage
            FROM _m_attempts
            """.trimIndent(),
        )
        db.execSQL(
            """
            INSERT INTO exam_audio (id, examId, displayName, fileName, durationMs, position)
            SELECT id, examId, displayName, fileName, durationMs, position FROM _m_audio
            """.trimIndent(),
        )
        // Every exam had exactly one document before this, so every mark
        // belongs to that exam's part at position zero, and its page number
        // was already a page number within it.
        db.execSQL(
            """
            INSERT INTO exam_marks
                (id, attemptId, partId, pageIndex, kind, x, y, width, height,
                 colorArgb, size, text, points, checked, sequence, createdAt)
            SELECT m.id, m.attemptId, p.id, m.pageIndex, m.kind, m.x, m.y, m.width, m.height,
                   m.colorArgb, m.size, m.text, m.points, m.checked, m.sequence, m.createdAt
            FROM _m_marks m
            JOIN _m_attempts a ON a.id = m.attemptId
            JOIN exam_parts p ON p.examId = a.examId AND p.position = 0
            """.trimIndent(),
        )

        db.execSQL("DROP TABLE _m_marks")
        db.execSQL("DROP TABLE _m_audio")
        db.execSQL("DROP TABLE _m_attempts")
        db.execSQL("DROP TABLE _m_parts")
    }
}

/**
 * Names the reader gave things, and the blank pages they write essays on.
 *
 * `documents.customName` is what a PDF is called *inside the app*. The file on
 * the phone keeps the name it has: the app has no write access to it and
 * renaming somebody's file because they wanted a tidier library would be a far
 * bigger thing than they asked for. Null means "call it what the file is
 * called", which is what every existing row means.
 *
 * `exam_parts.isNotes` marks a document the app generated rather than one the
 * reader imported — blank paper, appended to the paper so an essay is written
 * in the same place as the answers rather than in an app somewhere else.
 */
val MIGRATION_10_11 = object : Migration(10, 11) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE documents ADD COLUMN customName TEXT")
        db.execSQL("ALTER TABLE exam_parts ADD COLUMN isNotes INTEGER NOT NULL DEFAULT 0")
    }
}

/**
 * Turned text boxes.
 *
 * Zero for every mark that already exists, which is what they all are: text was
 * placed square to the page because there was no other option.
 */
val MIGRATION_11_12 = object : Migration(11, 12) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE exam_marks ADD COLUMN rotation REAL NOT NULL DEFAULT 0")
    }
}

/**
 * Exams leave the app, and their five tables go with them.
 *
 * The feature is gone in v4.1, and a database that keeps the tables would be a
 * database whose shape no longer matches the code: Room validates the schema on
 * open and refuses to start against extra tables it was not told about, so this
 * is not optional tidying.
 *
 * ### Order, and why it is this order
 *
 * The children are dropped before their parents. Dropping a table performs an
 * implicit `DELETE FROM` first, and with foreign keys enabled — which is how the
 * app runs — deleting a parent row fires `ON DELETE CASCADE` on the children
 * that point at it. Dropping `exams` while `exam_attempts` still existed would
 * therefore cascade into a table this statement has not reached yet, which
 * SQLite is entitled to complain about. Going upwards from the leaves means
 * every table is childless by the time it is dropped, and each cascade has
 * nothing left to reach.
 *
 * The *files* the rows named — the copied PDFs, the recordings — are deleted by
 * [com.david.llegeix.LlegeixApp] on the first launch after this upgrade. SQLite
 * cannot unlink anything, and dropping the tables here is what makes those files
 * unreachable, so the two halves have to happen together.
 */
val MIGRATION_12_13 = object : Migration(12, 13) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("DROP TABLE IF EXISTS exam_marks")
        db.execSQL("DROP TABLE IF EXISTS exam_audio")
        db.execSQL("DROP TABLE IF EXISTS exam_attempts")
        db.execSQL("DROP TABLE IF EXISTS exam_parts")
        db.execSQL("DROP TABLE IF EXISTS exams")
    }
}

/**
 * Records when a saved word was last answered about.
 *
 * Nullable with no default rather than a zero, because "never practised" and
 * "practised at the epoch" are different facts and only the first one is true of
 * every row that exists when this runs. Nothing is back-filled: the app has
 * never written this down before, so there is nothing to back-fill it from, and
 * a guess would put words in today's list that the reader never saw today.
 *
 * `dueAt` cannot be read as a substitute. It says when a word comes round next,
 * which depends on how many times it has been right — a fortnight for a word
 * well known, ten minutes for one just missed — so the day it was last seen
 * cannot be recovered from it.
 */
val MIGRATION_13_14 = object : Migration(13, 14) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN lastReviewedAt INTEGER")
    }
}

/**
 * Flashcards: decks the reader makes, and the cards in them.
 *
 * Two new tables and nothing else touched. The cards are not saved words and
 * do not share their table: a saved word is a note about something read, tied
 * to a page, and a card is vocabulary written by hand.
 *
 * Every column a card has is created here, including the ones later stages of
 * the feature fill in — the picture, the pronunciation, and a schedule for each
 * direction of study — so the feature costs one migration rather than one per
 * stage. The statements are Room's own `createSql` from `schemas/15.json`, so
 * a database that arrives here matches one built fresh at version 15 exactly.
 */
val MIGRATION_14_15 = object : Migration(14, 15) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `flashcard_decks` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `name` TEXT NOT NULL,
                `createdAt` INTEGER NOT NULL
            )
            """.trimIndent(),
        )
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `flashcards` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `deckId` INTEGER NOT NULL,
                `catalan` TEXT NOT NULL,
                `romanian` TEXT NOT NULL,
                `ipa` TEXT,
                `ipaApproximate` INTEGER NOT NULL,
                `imagePath` TEXT,
                `createdAt` INTEGER NOT NULL,
                `box` INTEGER NOT NULL,
                `dueAt` INTEGER NOT NULL,
                `reviewCount` INTEGER NOT NULL,
                `lastReviewedAt` INTEGER,
                `reverseBox` INTEGER NOT NULL,
                `reverseDueAt` INTEGER NOT NULL,
                `reverseReviewCount` INTEGER NOT NULL,
                `reverseLastReviewedAt` INTEGER,
                FOREIGN KEY(`deckId`) REFERENCES `flashcard_decks`(`id`)
                    ON UPDATE NO ACTION ON DELETE CASCADE
            )
            """.trimIndent(),
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_flashcards_deckId` ON `flashcards` (`deckId`)",
        )
    }
}
