package com.david.llegeix.data.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * Adds pinning, bookmarking, colours and read-later.
 *
 * Written out rather than falling back to destructive migration: folders and
 * bookmarks are hand-made by the user and cannot be regenerated by rescanning,
 * unlike the document rows themselves.
 */
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE folders ADD COLUMN isPinned INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE folders ADD COLUMN isBookmarked INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE folders ADD COLUMN colorArgb INTEGER")
        db.execSQL("ALTER TABLE documents ADD COLUMN isBookmarked INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE documents ADD COLUMN isReadLater INTEGER NOT NULL DEFAULT 0")
    }
}

/**
 * Adds saved words.
 *
 * The table mirrors [com.david.llegeix.data.db.entity.WordBookmarkEntity]: the
 * document reference is nullable and set to null rather than cascading, so a
 * word survives the PDF it came from being forgotten.
 */
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `word_bookmarks` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `word` TEXT NOT NULL,
                `translation` TEXT,
                `ipa` TEXT,
                `context` TEXT,
                `documentUri` TEXT,
                `displayName` TEXT,
                `pageIndex` INTEGER NOT NULL,
                `lineNumber` INTEGER NOT NULL,
                `createdAt` INTEGER NOT NULL,
                FOREIGN KEY(`documentUri`) REFERENCES `documents`(`uriString`)
                    ON UPDATE NO ACTION ON DELETE SET NULL
            )
            """.trimIndent(),
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_word_bookmarks_documentUri` " +
                "ON `word_bookmarks` (`documentUri`)",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_word_bookmarks_word` " +
                "ON `word_bookmarks` (`word`)",
        )
    }
}

/**
 * Adds tags.
 *
 * Two tables: the tags themselves, and the pairings. Both cascade on delete, so
 * removing a document or a tag cleans up its links rather than leaving rows
 * pointing at nothing.
 */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `tags` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `name` TEXT NOT NULL,
                `colorArgb` INTEGER NOT NULL,
                `createdAt` INTEGER NOT NULL
            )
            """.trimIndent(),
        )
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_tags_name` ON `tags` (`name`)")
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `document_tags` (
                `documentUri` TEXT NOT NULL,
                `tagId` INTEGER NOT NULL,
                PRIMARY KEY(`documentUri`, `tagId`),
                FOREIGN KEY(`documentUri`) REFERENCES `documents`(`uriString`)
                    ON UPDATE NO ACTION ON DELETE CASCADE,
                FOREIGN KEY(`tagId`) REFERENCES `tags`(`id`)
                    ON UPDATE NO ACTION ON DELETE CASCADE
            )
            """.trimIndent(),
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_document_tags_tagId` " +
                "ON `document_tags` (`tagId`)",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_document_tags_documentUri` " +
                "ON `document_tags` (`documentUri`)",
        )
    }
}

/**
 * Adds the per-folder decisions behind the sources screen.
 *
 * Nothing is inserted: an empty table means every folder inside every granted
 * source is shown, which is exactly how the app behaved before this table
 * existed.
 */
val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `folder_rules` (
                `path` TEXT NOT NULL,
                `included` INTEGER NOT NULL,
                PRIMARY KEY(`path`)
            )
            """.trimIndent(),
        )
    }
}

/**
 * Keeps what a saved word meant in the line it was saved from.
 *
 * All three columns are nullable with no default, which is what makes this
 * safe: a word saved before v3.1 simply has no contextual reading, and the
 * screen already draws each of these only when it is there. Nothing is
 * back-filled, because the reading cannot be recomputed without the translator
 * and the page, and a guessed one would be worse than none.
 */
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN contextTranslation TEXT")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN senseTranslation TEXT")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN senseSource TEXT")
    }
}

/**
 * Records how long a document is, so the app can say how far through it you are.
 *
 * Nullable with no default rather than a zero: "not opened yet" and "a document
 * of no pages" are different facts, and only the first is true of every row
 * that exists when this runs. Nothing is back-filled — the count comes from
 * opening the file, and opening every PDF the library has ever seen in a
 * migration would block the first launch after an update for as long as the
 * reader's library is large.
 */
val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE documents ADD COLUMN pageCount INTEGER")
    }
}

/**
 * Gives every saved word a place in the practice deck.
 *
 * The three columns have defaults rather than being nullable, because unlike
 * the columns added in 5→6 there is a right answer for a word saved before this
 * existed: box zero, due now, never reviewed. A vocabulary list that has been
 * building for months should arrive in the new deck as a deck, not as a hundred
 * rows the scheduler has to be taught to ignore.
 */
val MIGRATION_7_8 = object : Migration(7, 8) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN box INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN dueAt INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE word_bookmarks ADD COLUMN reviewCount INTEGER NOT NULL DEFAULT 0")
    }
}
