package com.david.catalanpdfreader.data.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * Adds pinning, bookmarking, colours and read-later.
 *
 * Written out rather than falling back to destructive migration: folders and
 * bookmarks are hand-made by the user and cannot be regenerated by rescanning,
 * unlike the document rows themselves.
 */
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE folders ADD COLUMN isPinned INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE folders ADD COLUMN isBookmarked INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE folders ADD COLUMN colorArgb INTEGER")
        db.execSQL("ALTER TABLE documents ADD COLUMN isBookmarked INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE documents ADD COLUMN isReadLater INTEGER NOT NULL DEFAULT 0")
    }
}
