package com.david.llegeix.data

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.david.llegeix.data.db.LlegeixDatabase
import com.david.llegeix.data.db.MIGRATION_1_2
import com.david.llegeix.data.db.MIGRATION_2_3
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

private const val TEST_DB = "migration-test.db"

/**
 * Verifies the v1 to v2 upgrade preserves user-made data.
 *
 * Worth an instrumented test rather than trusting the ALTER statements: folders
 * and bookmarks cannot be regenerated by rescanning storage, and a migration
 * that throws takes the app down on launch rather than failing quietly.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        LlegeixDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory(),
    )

    @Test
    fun migrate1To2_keepsFoldersDocumentsAndBookmarks() {
        helper.createDatabase(TEST_DB, 1).use { db ->
            db.execSQL(
                "INSERT INTO folders (id, name, createdAt) VALUES (1, 'Gramatica', 100)",
            )
            db.execSQL(
                """
                INSERT INTO documents (uriString, displayName, folderId, highlightColor, addedAt)
                VALUES ('content://test/1', 'verbs.pdf', 1, NULL, 200)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO bookmarks (id, documentUri, pageIndex, label, highlightColor, createdAt)
                VALUES (1, 'content://test/1', 4, 'irregulars', NULL, 300)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO recently_viewed (documentUri, viewedAt, lastPageIndex)
                VALUES ('content://test/1', 400, 4)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 2, true, MIGRATION_1_2)

        db.query("SELECT name, isPinned, isBookmarked, colorArgb FROM folders").use { cursor ->
            assertTrue("folder row survived", cursor.moveToFirst())
            assertEquals("Gramatica", cursor.getString(0))
            assertEquals("new folders default to unpinned", 0, cursor.getInt(1))
            assertEquals("new folders default to unbookmarked", 0, cursor.getInt(2))
            assertTrue("colour defaults to unset", cursor.isNull(3))
        }

        db.query(
            "SELECT displayName, folderId, isBookmarked, isReadLater FROM documents",
        ).use { cursor ->
            assertTrue("document row survived", cursor.moveToFirst())
            assertEquals("verbs.pdf", cursor.getString(0))
            assertEquals("folder membership preserved", 1, cursor.getInt(1))
            assertEquals(0, cursor.getInt(2))
            assertEquals(0, cursor.getInt(3))
        }

        db.query("SELECT pageIndex, label FROM bookmarks").use { cursor ->
            assertTrue("page bookmark survived", cursor.moveToFirst())
            assertEquals(4, cursor.getInt(0))
            assertEquals("irregulars", cursor.getString(1))
        }

        db.query("SELECT lastPageIndex FROM recently_viewed").use { cursor ->
            assertTrue("reading position survived", cursor.moveToFirst())
            assertEquals(4, cursor.getInt(0))
        }
    }

    @Test
    fun migrate2To3_addsSavedWordsAndKeepsEverythingElse() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO folders (id, name, createdAt, isPinned, isBookmarked, colorArgb)
                VALUES (1, 'Lectures', 100, 0, 0, NULL)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'princep.pdf', 1, NULL, 200, 0, 0)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 3, true, MIGRATION_2_3)

        // The new table is usable, including the nullable document reference.
        db.execSQL(
            """
            INSERT INTO word_bookmarks
                (word, translation, ipa, context, documentUri, displayName,
                 pageIndex, lineNumber, createdAt)
            VALUES ('serp', 'snake', 'sɛrp', 'una serp boa', 'content://test/1',
                    'princep.pdf', 0, 2, 500)
            """.trimIndent(),
        )
        db.query("SELECT word, translation, lineNumber FROM word_bookmarks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("serp", cursor.getString(0))
            assertEquals("snake", cursor.getString(1))
            assertEquals(2, cursor.getInt(2))
        }

        // Nothing that was already there was disturbed.
        db.query("SELECT displayName FROM documents").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("princep.pdf", cursor.getString(0))
        }
    }

    /**
     * The whole path a real device takes: an install from before folders even
     * had colours, upgraded twice in a row.
     */
    @Test
    fun migrate1To3_runsBothStepsInSequence() {
        helper.createDatabase(TEST_DB, 1).use { db ->
            db.execSQL("INSERT INTO folders (id, name, createdAt) VALUES (1, 'Vell', 100)")
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 3, true, MIGRATION_1_2, MIGRATION_2_3)

        db.query("SELECT name, isPinned FROM folders").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("Vell", cursor.getString(0))
            assertEquals(0, cursor.getInt(1))
        }
        db.query("SELECT COUNT(*) FROM word_bookmarks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
    }
}
