package com.david.llegeix.data

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.david.llegeix.data.db.LlegeixDatabase
import com.david.llegeix.data.db.MIGRATION_1_2
import com.david.llegeix.data.db.MIGRATION_2_3
import com.david.llegeix.data.db.MIGRATION_3_4
import com.david.llegeix.data.db.MIGRATION_4_5
import com.david.llegeix.data.db.MIGRATION_5_6
import com.david.llegeix.data.db.MIGRATION_6_7
import com.david.llegeix.data.db.MIGRATION_7_8
import com.david.llegeix.data.db.MIGRATION_8_9
import com.david.llegeix.data.db.MIGRATION_9_10
import com.david.llegeix.data.db.MIGRATION_10_11
import com.david.llegeix.data.db.MIGRATION_11_12
import com.david.llegeix.data.db.MIGRATION_12_13
import com.david.llegeix.data.db.MIGRATION_13_14
import com.david.llegeix.data.db.MIGRATION_14_15
import com.david.llegeix.data.db.MIGRATION_15_16
import com.david.llegeix.data.db.MIGRATION_16_17
import com.david.llegeix.data.db.MIGRATION_17_18
import com.david.llegeix.data.db.MIGRATION_18_19
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

private const val TEST_DB = "migration-test.db"

/**
 * Verifies the v1 to v2 upgrade preserves user-made data.
 *
 * Worth an instrumented test rather than trusting the ALTER statements: folders
 * and bookmarks cannot be regenerated by rescanning storage, and a migration
 * that throws takes the app down on launch rather than failing quietly.
 */
@RunWith(AndroidJUnit4::class)
class MigrationTest {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        LlegeixDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory(),
    )

    @Test
    fun migrate1To2_keepsFoldersDocumentsAndBookmarks() {
        helper.createDatabase(TEST_DB, 1).use { db ->
            db.execSQL(
                "INSERT INTO folders (id, name, createdAt) VALUES (1, 'Gramatica', 100)",
            )
            db.execSQL(
                """
                INSERT INTO documents (uriString, displayName, folderId, highlightColor, addedAt)
                VALUES ('content://test/1', 'verbs.pdf', 1, NULL, 200)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO bookmarks (id, documentUri, pageIndex, label, highlightColor, createdAt)
                VALUES (1, 'content://test/1', 4, 'irregulars', NULL, 300)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO recently_viewed (documentUri, viewedAt, lastPageIndex)
                VALUES ('content://test/1', 400, 4)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 2, true, MIGRATION_1_2)

        db.query("SELECT name, isPinned, isBookmarked, colorArgb FROM folders").use { cursor ->
            assertTrue("folder row survived", cursor.moveToFirst())
            assertEquals("Gramatica", cursor.getString(0))
            assertEquals("new folders default to unpinned", 0, cursor.getInt(1))
            assertEquals("new folders default to unbookmarked", 0, cursor.getInt(2))
            assertTrue("colour defaults to unset", cursor.isNull(3))
        }

        db.query(
            "SELECT displayName, folderId, isBookmarked, isReadLater FROM documents",
        ).use { cursor ->
            assertTrue("document row survived", cursor.moveToFirst())
            assertEquals("verbs.pdf", cursor.getString(0))
            assertEquals("folder membership preserved", 1, cursor.getInt(1))
            assertEquals(0, cursor.getInt(2))
            assertEquals(0, cursor.getInt(3))
        }

        db.query("SELECT pageIndex, label FROM bookmarks").use { cursor ->
            assertTrue("page bookmark survived", cursor.moveToFirst())
            assertEquals(4, cursor.getInt(0))
            assertEquals("irregulars", cursor.getString(1))
        }

        db.query("SELECT lastPageIndex FROM recently_viewed").use { cursor ->
            assertTrue("reading position survived", cursor.moveToFirst())
            assertEquals(4, cursor.getInt(0))
        }
    }

    @Test
    fun migrate2To3_addsSavedWordsAndKeepsEverythingElse() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO folders (id, name, createdAt, isPinned, isBookmarked, colorArgb)
                VALUES (1, 'Lectures', 100, 0, 0, NULL)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'princep.pdf', 1, NULL, 200, 0, 0)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 3, true, MIGRATION_2_3)

        // The new table is usable, including the nullable document reference.
        db.execSQL(
            """
            INSERT INTO word_bookmarks
                (word, translation, ipa, context, documentUri, displayName,
                 pageIndex, lineNumber, createdAt)
            VALUES ('serp', 'snake', 'sɛrp', 'una serp boa', 'content://test/1',
                    'princep.pdf', 0, 2, 500)
            """.trimIndent(),
        )
        db.query("SELECT word, translation, lineNumber FROM word_bookmarks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("serp", cursor.getString(0))
            assertEquals("snake", cursor.getString(1))
            assertEquals(2, cursor.getInt(2))
        }

        // Nothing that was already there was disturbed.
        db.query("SELECT displayName FROM documents").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("princep.pdf", cursor.getString(0))
        }
    }

    /**
     * The whole path a real device takes: an install from before folders even
     * had colours, upgraded twice in a row.
     */
    @Test
    fun migrate1To3_runsBothStepsInSequence() {
        helper.createDatabase(TEST_DB, 1).use { db ->
            db.execSQL("INSERT INTO folders (id, name, createdAt) VALUES (1, 'Vell', 100)")
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 3, true, MIGRATION_1_2, MIGRATION_2_3)

        db.query("SELECT name, isPinned FROM folders").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("Vell", cursor.getString(0))
            assertEquals(0, cursor.getInt(1))
        }
        db.query("SELECT COUNT(*) FROM word_bookmarks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
    }

    @Test
    fun migrate3To4_addsTagsAndKeepsSavedWords() {
        helper.createDatabase(TEST_DB, 3).use { db ->
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'princep.pdf', NULL, NULL, 200, 0, 0)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt)
                VALUES ('serp', 'snake', 'sɛɾp', 'una serp boa', 'content://test/1',
                        'princep.pdf', 0, 2, 500)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 4, true, MIGRATION_3_4)

        db.execSQL(
            "INSERT INTO tags (name, colorArgb, createdAt) VALUES ('Gramatica', -12345, 600)",
        )
        db.execSQL(
            "INSERT INTO document_tags (documentUri, tagId) VALUES ('content://test/1', 1)",
        )
        db.query(
            """
            SELECT t.name FROM document_tags dt
            INNER JOIN tags t ON t.id = dt.tagId
            WHERE dt.documentUri = 'content://test/1'
            """.trimIndent(),
        ).use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("Gramatica", cursor.getString(0))
        }

        // The words saved before the upgrade are still there.
        db.query("SELECT word FROM word_bookmarks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("serp", cursor.getString(0))
        }
    }

    @Test
    fun deletingATagUnfilesItEverywhere() {
        helper.createDatabase(TEST_DB, 3).use { db ->
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'a.pdf', NULL, NULL, 1, 0, 0)
                """.trimIndent(),
            )
        }
        val db = helper.runMigrationsAndValidate(TEST_DB, 4, true, MIGRATION_3_4)
        db.execSQL("PRAGMA foreign_keys=ON")
        db.execSQL("INSERT INTO tags (name, colorArgb, createdAt) VALUES ('Lectures', 1, 1)")
        db.execSQL("INSERT INTO document_tags (documentUri, tagId) VALUES ('content://test/1', 1)")

        db.execSQL("DELETE FROM tags WHERE id = 1")

        db.query("SELECT COUNT(*) FROM document_tags").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
    }

    @Test
    fun migrate4To5AddsFolderRulesAndKeepsEverythingElse() {
        helper.createDatabase(TEST_DB, 4).use { db ->
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'princep.pdf', NULL, NULL, 200, 0, 0)
                """.trimIndent(),
            )
            db.execSQL(
                "INSERT INTO tags (name, colorArgb, createdAt) VALUES ('Historia', -1, 1)",
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 5, true, MIGRATION_4_5)

        // The new table is usable, and it starts empty, which is what makes the
        // upgrade invisible: no rules means every folder is still shown.
        db.query("SELECT COUNT(*) FROM folder_rules").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
        db.execSQL(
            "INSERT INTO folder_rules (path, included) VALUES ('Documents/Feina', 0)",
        )
        db.query("SELECT included FROM folder_rules WHERE path = 'Documents/Feina'").use {
            assertTrue(it.moveToFirst())
            assertEquals(0, it.getInt(0))
        }

        // Nothing from before the upgrade was disturbed.
        db.query("SELECT displayName FROM documents").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("princep.pdf", cursor.getString(0))
        }
        db.query("SELECT name FROM tags").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("Historia", cursor.getString(0))
        }
    }

    @Test
    fun migrate5To6_keepsSavedWordsAndAcceptsTheContextualReading() {
        helper.createDatabase(TEST_DB, 5).use { db ->
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt)
                VALUES ('cap', 'no', 'kap', 'Va lligar el cap de la corda', NULL,
                        'prova.pdf', 0, 5, 500)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 6, true, MIGRATION_5_6)

        // A word saved before v3.1 keeps everything it had and simply has no
        // contextual reading, which is what the screen already draws around.
        db.query(
            "SELECT word, translation, contextTranslation, senseTranslation, senseSource " +
                "FROM word_bookmarks",
        ).use { cursor ->
            assertTrue("saved word survived", cursor.moveToFirst())
            assertEquals("cap", cursor.getString(0))
            assertEquals("no", cursor.getString(1))
            assertTrue("no line translation for an old row", cursor.isNull(2))
            assertTrue("no contextual reading for an old row", cursor.isNull(3))
            assertTrue("no expression for an old row", cursor.isNull(4))
        }

        // And a word saved after it can carry both kinds of reading.
        db.execSQL(
            """
            INSERT INTO word_bookmarks
                (word, translation, ipa, context, contextTranslation,
                 senseTranslation, senseSource, documentUri, displayName,
                 pageIndex, lineNumber, createdAt)
            VALUES ('planta', 'plant', 'plantə', 'La planta baixa era buida',
                    'The ground floor was empty', 'floor', 'planta baixa',
                    NULL, 'prova.pdf', 0, 3, 600)
            """.trimIndent(),
        )
        db.query(
            "SELECT senseTranslation, senseSource FROM word_bookmarks WHERE word = 'planta'",
        ).use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("floor", cursor.getString(0))
            assertEquals("planta baixa", cursor.getString(1))
        }
    }

    /**
     * Page counts, added so the library can draw a bar rather than print a page
     * number.
     *
     * The column is deliberately nullable and deliberately not back-filled: a
     * document that has never been opened has no page count, and the test
     * checks exactly that rather than a zero standing in for it.
     */
    @Test
    fun migrate6To7_addsPageCountAndLeavesItUnknown() {
        helper.createDatabase(TEST_DB, 6).use { db ->
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'princep.pdf', NULL, NULL, 200, 0, 0)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO recently_viewed (documentUri, viewedAt, lastPageIndex)
                VALUES ('content://test/1', 400, 12)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 7, true, MIGRATION_6_7)

        db.query("SELECT displayName, pageCount FROM documents").use { cursor ->
            assertTrue("document row survived", cursor.moveToFirst())
            assertEquals("princep.pdf", cursor.getString(0))
            assertTrue("a never-opened document has no page count", cursor.isNull(1))
        }
        db.query("SELECT lastPageIndex FROM recently_viewed").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("reading position untouched", 12, cursor.getInt(0))
        }

        db.execSQL("UPDATE documents SET pageCount = 210 WHERE uriString = 'content://test/1'")
        db.query("SELECT pageCount FROM documents").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(210, cursor.getInt(0))
        }
    }

    /**
     * A vocabulary list that predates the practice deck arrives as a deck.
     *
     * The three columns have defaults rather than being nullable precisely so
     * this is true: every word already saved comes through in box zero and due
     * immediately, which is what a word nobody has ever been asked about is.
     */
    @Test
    fun migrate7To8_putsExistingWordsInTheDeck() {
        helper.createDatabase(TEST_DB, 7).use { db ->
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt)
                VALUES ('enrenou', 'commotion', 'ənrəˈnɔw', 'quin enrenou', NULL,
                        NULL, 3, 7, 500)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 8, true, MIGRATION_7_8)

        db.query("SELECT word, box, dueAt, reviewCount FROM word_bookmarks").use { cursor ->
            assertTrue("saved word survived", cursor.moveToFirst())
            assertEquals("enrenou", cursor.getString(0))
            assertEquals("starts in the first box", 0, cursor.getInt(1))
            assertEquals("due straight away", 0L, cursor.getLong(2))
            assertEquals("never reviewed", 0, cursor.getInt(3))
        }
    }

    /**
     * Exams arrive without touching anything the reader already had.
     *
     * Three new tables and no altered column, so the check is in two halves:
     * that the library came through untouched, and that the new tables actually
     * behave the way the feature needs them to — which for exams means the
     * cascade, since deleting a paper has to take its sittings with it rather
     * than leave answers pointing at nothing.
     */
    @Test
    fun migrate8To9_addsExamsAndLeavesTheLibraryAlone() {
        helper.createDatabase(TEST_DB, 8).use { db ->
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater)
                VALUES ('content://test/1', 'princep.pdf', NULL, NULL, 200, 0, 0)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt, box, dueAt, reviewCount)
                VALUES ('enrenou', 'commotion', 'ənrəˈnɔw', 'quin enrenou', NULL,
                        NULL, 3, 7, 500, 1, 900, 2)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 9, true, MIGRATION_8_9)

        // The upgrade is invisible to somebody who never opens the new tab.
        db.query("SELECT displayName FROM documents").use { cursor ->
            assertTrue("document row survived", cursor.moveToFirst())
            assertEquals("princep.pdf", cursor.getString(0))
        }
        db.query("SELECT word, box FROM word_bookmarks").use { cursor ->
            assertTrue("saved word survived", cursor.moveToFirst())
            assertEquals("enrenou", cursor.getString(0))
            assertEquals("its place in the deck survived", 1, cursor.getInt(1))
        }
        db.query("SELECT COUNT(*) FROM exams").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("no exams until one is imported", 0, cursor.getInt(0))
        }

        // A paper, a sitting of it, and a recording attached to it.
        db.execSQL("PRAGMA foreign_keys=ON")
        db.execSQL(
            """
            INSERT INTO exams
                (id, title, sourceName, fileName, pageCount,
                 answerKeyFileName, answerKeyPageCount, createdAt)
            VALUES (1, 'C1 mostra', 'c1-mostra.pdf', 'abc.pdf', 12, NULL, NULL, 1000)
            """.trimIndent(),
        )
        db.execSQL(
            """
            INSERT INTO exam_attempts
                (id, examId, label, startedAt, lastOpenedAt, finishedAt, lastPage)
            VALUES (1, 1, '1', 1100, 1100, NULL, 0)
            """.trimIndent(),
        )
        db.execSQL(
            """
            INSERT INTO exam_audio (id, examId, displayName, fileName, durationMs, position)
            VALUES (1, 1, 'comprensio.mp3', 'def.mp3', 180000, 0)
            """.trimIndent(),
        )

        db.query("SELECT label, finishedAt FROM exam_attempts WHERE examId = 1").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("1", cursor.getString(0))
            assertTrue("a fresh sitting is not finished", cursor.isNull(1))
        }

        // A mark written on that sitting, stored as fractions of the page.
        db.execSQL(
            """
            INSERT INTO exam_marks
                (id, attemptId, pageIndex, kind, x, y, width, height,
                 colorArgb, size, text, points, checked, sequence, createdAt)
            VALUES (1, 1, 0, 'INK', 0.1, 0.2, 0.3, 0.05, -16777216, 0.004,
                    NULL, '0.1,0.2 0.4,0.25', 0, 1, 1200)
            """.trimIndent(),
        )
        db.query("SELECT kind, points FROM exam_marks WHERE attemptId = 1").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("INK", cursor.getString(0))
            assertEquals("0.1,0.2 0.4,0.25", cursor.getString(1))
        }

        // Deleting the paper takes the sitting, its marks and the recording with
        // it, so nothing is left behind pointing at a page that no longer
        // exists. The marks go by a second hop of the cascade — through the
        // attempt, not straight from the exam — which is the part worth testing.
        db.execSQL("DELETE FROM exams WHERE id = 1")
        db.query("SELECT COUNT(*) FROM exam_attempts").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
        db.query("SELECT COUNT(*) FROM exam_marks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("marks follow their attempt", 0, cursor.getInt(0))
        }
        db.query("SELECT COUNT(*) FROM exam_audio").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
    }

    /**
     * An exam becomes a paper of documents, and nobody's answers are lost.
     *
     * This is the migration with real teeth in it. Removing three columns from
     * `exams` means recreating a table whose children cascade on delete, and the
     * obvious way to do that deletes every attempt and every mark on the way
     * past — silently, leaving a database that validates perfectly. So the test
     * is not "does it run": it is that every row is still there afterwards, and
     * that each mark ended up on the document its own attempt's exam owns.
     */
    @Test
    fun migrate9To10_makesEachExamAPaperOfOneDocumentAndKeepsEveryMark() {
        helper.createDatabase(TEST_DB, 9).use { db ->
            db.execSQL(
                """
                INSERT INTO exams
                    (id, title, sourceName, fileName, pageCount,
                     answerKeyFileName, answerKeyPageCount, createdAt)
                VALUES (1, 'C1 mostra', 'c1.pdf', 'aaa.pdf', 12, 'key.pdf', 4, 1000),
                       (2, 'B2 mostra', 'b2.pdf', 'bbb.pdf', 8, NULL, NULL, 2000)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO exam_attempts
                    (id, examId, label, startedAt, lastOpenedAt, finishedAt, lastPage)
                VALUES (1, 1, '1', 1100, 1150, NULL, 3),
                       (2, 1, '2', 1200, 1250, 1300, 0),
                       (3, 2, '1', 2100, 2150, NULL, 1)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO exam_audio (id, examId, displayName, fileName, durationMs, position)
                VALUES (1, 1, 'listen.mp3', 'ccc.mp3', 180000, 0)
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO exam_marks
                    (id, attemptId, pageIndex, kind, x, y, width, height,
                     colorArgb, size, text, points, checked, sequence, createdAt)
                VALUES (1, 1, 0, 'INK', 0.1, 0.2, 0.3, 0.05, -16777216, 0.004,
                        NULL, '0.1,0.2 0.4,0.25', 0, 1, 1200),
                       (2, 1, 3, 'TICK', 0.5, 0.5, 0.03, 0.03, -16777216, 0.03,
                        NULL, NULL, 1, 2, 1300),
                       (3, 3, 1, 'TEXT', 0.2, 0.4, 0.3, 0.03, -16777216, 0.022,
                        'resposta', NULL, 0, 1, 2200)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 10, true, MIGRATION_9_10)

        // Nothing was lost on the way past the table rebuild.
        for ((table, expected) in listOf(
            "exams" to 2,
            "exam_parts" to 2,
            "exam_attempts" to 3,
            "exam_audio" to 1,
            "exam_marks" to 3,
        )) {
            db.query("SELECT COUNT(*) FROM $table").use { cursor ->
                assertTrue(cursor.moveToFirst())
                assertEquals("$table survived the rebuild", expected, cursor.getInt(0))
            }
        }

        // The one document each exam had is now its first part.
        db.query(
            "SELECT examId, sourceName, fileName, pageCount, position " +
                "FROM exam_parts ORDER BY examId",
        ).use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(1, cursor.getInt(0))
            assertEquals("c1.pdf", cursor.getString(1))
            assertEquals("aaa.pdf", cursor.getString(2))
            assertEquals(12, cursor.getInt(3))
            assertEquals("the only document is the first one", 0, cursor.getInt(4))
        }

        // The answer sheet and the attempts came through untouched.
        db.query("SELECT answerKeyFileName, answerKeyPageCount FROM exams WHERE id = 1").use {
            assertTrue(it.moveToFirst())
            assertEquals("key.pdf", it.getString(0))
            assertEquals(4, it.getInt(1))
        }
        db.query("SELECT label, finishedAt, lastPage FROM exam_attempts WHERE id = 2").use {
            assertTrue(it.moveToFirst())
            assertEquals("2", it.getString(0))
            assertEquals(1300L, it.getLong(1))
        }

        // And every mark sits on a document belonging to its own attempt's exam,
        // which is the one thing a wrong join here would get silently wrong.
        db.query(
            """
            SELECT COUNT(*) FROM exam_marks m
            JOIN exam_attempts a ON a.id = m.attemptId
            JOIN exam_parts p ON p.id = m.partId
            WHERE p.examId <> a.examId
            """.trimIndent(),
        ).use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("no mark landed on another exam's document", 0, cursor.getInt(0))
        }
        db.query("SELECT text FROM exam_marks WHERE id = 3").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("resposta", cursor.getString(0))
        }

        // The rebuilt foreign keys still bite: removing a document takes the
        // marks written on it, and removing the paper takes everything.
        db.execSQL("PRAGMA foreign_keys=ON")
        db.execSQL("DELETE FROM exams WHERE id = 1")
        db.query("SELECT COUNT(*) FROM exam_parts").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(1, cursor.getInt(0))
        }
        db.query("SELECT COUNT(*) FROM exam_marks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("only exam 2's mark is left", 1, cursor.getInt(0))
        }
    }

    /**
     * Exams leave, and nothing the reader built leaves with them.
     *
     * The seeded database is a populated one on purpose. Dropping a parent table
     * with foreign keys on performs an implicit delete first, which fires every
     * `ON DELETE CASCADE` hanging off it — so a migration that dropped `exams`
     * before its children would be reaching into tables it had not got to yet.
     * The five drops go upwards from the leaves, and `PRAGMA foreign_keys=ON`
     * here is what makes this test able to tell the difference.
     */
    @Test
    fun migrate12To13_dropsEveryExamTableAndKeepsTheLibrary() {
        helper.createDatabase(TEST_DB, 12).use { db ->
            db.execSQL("PRAGMA foreign_keys=ON")
            db.execSQL("INSERT INTO folders (id, name, createdAt, isPinned, isBookmarked) " +
                "VALUES (1, 'Gramatica', 100, 0, 0)")
            db.execSQL(
                """
                INSERT INTO documents
                    (uriString, displayName, folderId, highlightColor, addedAt,
                     isBookmarked, isReadLater, pageCount, customName)
                VALUES ('content://test/1', 'princep.pdf', 1, NULL, 200, 1, 0, 96, 'El Princep')
                """.trimIndent(),
            )
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt, box, dueAt, reviewCount)
                VALUES ('enrenou', 'commotion', 'ənrəˈnɔw', 'quin enrenou',
                        'content://test/1', 'princep.pdf', 3, 7, 500, 1, 900, 2)
                """.trimIndent(),
            )
            // A paper, a document in it, a sitting, a recording and a mark: one
            // row in each of the five tables that are about to go.
            db.execSQL(
                "INSERT INTO exams (id, title, answerKeyFileName, answerKeyPageCount, createdAt) " +
                    "VALUES (1, 'C1 mostra', NULL, NULL, 1000)",
            )
            db.execSQL(
                "INSERT INTO exam_parts (id, examId, sourceName, fileName, pageCount, " +
                    "position, isNotes) VALUES (1, 1, 'c1.pdf', 'abc.pdf', 12, 0, 0)",
            )
            db.execSQL(
                "INSERT INTO exam_attempts (id, examId, label, startedAt, lastOpenedAt, " +
                    "finishedAt, lastPage) VALUES (1, 1, '1', 1100, 1200, NULL, 3)",
            )
            db.execSQL(
                "INSERT INTO exam_audio (id, examId, displayName, fileName, durationMs, " +
                    "position) VALUES (1, 1, 'Pista 1', 'a.m4a', 60000, 0)",
            )
            db.execSQL(
                """
                INSERT INTO exam_marks
                    (id, attemptId, partId, pageIndex, kind, x, y, width, height,
                     colorArgb, size, text, points, checked, sequence, createdAt, rotation)
                VALUES (1, 1, 1, 2, 'TEXT', 0.1, 0.2, 0.3, 0.05, -16777216, 14.0,
                        'resposta', NULL, 0, 0, 1300, 0.0)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 13, true, MIGRATION_12_13)

        db.query(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name LIKE 'exam%'",
        ).use { cursor ->
            assertEquals("every exam table is gone", 0, cursor.count)
        }
        // The half of the upgrade that matters: a reader who never sat an exam
        // should not be able to tell this happened.
        db.query("SELECT displayName, customName, isBookmarked FROM documents").use { cursor ->
            assertTrue("document row survived", cursor.moveToFirst())
            assertEquals("princep.pdf", cursor.getString(0))
            assertEquals("the reader's own name survived", "El Princep", cursor.getString(1))
            assertEquals("and the star on it", 1, cursor.getInt(2))
        }
        db.query("SELECT word, box FROM word_bookmarks").use { cursor ->
            assertTrue("saved word survived", cursor.moveToFirst())
            assertEquals("enrenou", cursor.getString(0))
            assertEquals("its place in the deck survived", 1, cursor.getInt(1))
        }
        db.query("SELECT name FROM folders").use { cursor ->
            assertTrue("folder survived", cursor.moveToFirst())
            assertEquals("Gramatica", cursor.getString(0))
        }
    }

    /**
     * Words gain the day they were last practised, and nothing is guessed.
     *
     * The new column is nullable with no default on purpose: "never practised"
     * and "practised at the epoch" are different facts, and a back-filled zero
     * would be the app claiming to know a day it has never recorded.
     */
    @Test
    fun migrate13To14_addsLastReviewedAtAndLeavesItUnknown() {
        helper.createDatabase(TEST_DB, 13).use { db ->
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (id, word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt, box, dueAt, reviewCount)
                VALUES (1, 'enrenou', 'commotion', 'ənrəˈnɔw', 'quin enrenou', NULL,
                        NULL, 3, 7, 500, 2, 900, 4)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 14, true, MIGRATION_13_14)

        db.query(
            "SELECT word, box, reviewCount, lastReviewedAt FROM word_bookmarks",
        ).use { cursor ->
            assertTrue("saved word survived", cursor.moveToFirst())
            assertEquals("enrenou", cursor.getString(0))
            assertEquals("its place in the deck survived", 2, cursor.getInt(1))
            assertEquals("and its count of answers", 4, cursor.getInt(2))
            assertTrue(
                "a word practised before this existed has no recorded day",
                cursor.isNull(3),
            )
        }
    }

    /**
     * Flashcards arrive as two empty tables, and nothing already there moves.
     *
     * Checked against a saved word in particular, because the cards look like
     * saved words — a box, a due date, a count — and a migration that mixed the
     * two up would be the worst kind of quiet.
     */
    @Test
    fun migrate14To15_addsEmptyFlashcardTablesAndKeepsSavedWords() {
        helper.createDatabase(TEST_DB, 14).use { db ->
            db.execSQL(
                """
                INSERT INTO word_bookmarks
                    (id, word, translation, ipa, context, documentUri, displayName,
                     pageIndex, lineNumber, createdAt, box, dueAt, reviewCount,
                     lastReviewedAt)
                VALUES (1, 'enrenou', 'commotion', 'ənrəˈnɔw', 'quin enrenou', NULL,
                        NULL, 3, 7, 500, 2, 900, 4, 800)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 15, true, MIGRATION_14_15)

        db.query("SELECT word, box, dueAt, lastReviewedAt FROM word_bookmarks").use { cursor ->
            assertTrue("saved word survived", cursor.moveToFirst())
            assertEquals("enrenou", cursor.getString(0))
            assertEquals(2, cursor.getInt(1))
            assertEquals(900L, cursor.getLong(2))
            assertEquals(800L, cursor.getLong(3))
        }
        db.query("SELECT COUNT(*) FROM flashcard_decks").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("no decks are invented", 0, cursor.getInt(0))
        }
        db.query("SELECT COUNT(*) FROM flashcards").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("and no cards", 0, cursor.getInt(0))
        }
    }

    /** A deck owns its cards: deleting it takes them, and leaves other decks alone. */
    @Test
    fun deletingADeckDeletesItsCards() {
        helper.createDatabase(TEST_DB, 14).close()
        val db = helper.runMigrationsAndValidate(TEST_DB, 15, true, MIGRATION_14_15)
        db.execSQL("PRAGMA foreign_keys=ON")
        db.execSQL("INSERT INTO flashcard_decks (id, name, createdAt) VALUES (1, 'Menjar', 1)")
        db.execSQL("INSERT INTO flashcard_decks (id, name, createdAt) VALUES (2, 'Verbs', 1)")
        for ((deck, catalan, romanian) in listOf(
            Triple(1, "pa", "pâine"),
            Triple(1, "aigua", "apă"),
            Triple(2, "menjar", "a mânca"),
        )) {
            db.execSQL(
                """
                INSERT INTO flashcards
                    (deckId, catalan, romanian, ipa, ipaApproximate, imagePath, createdAt,
                     box, dueAt, reviewCount, lastReviewedAt,
                     reverseBox, reverseDueAt, reverseReviewCount, reverseLastReviewedAt)
                VALUES ($deck, '$catalan', '$romanian', NULL, 0, NULL, 1,
                        0, 0, 0, NULL, 0, 0, 0, NULL)
                """.trimIndent(),
            )
        }

        db.execSQL("DELETE FROM flashcard_decks WHERE id = 1")

        db.query("SELECT catalan FROM flashcards").use { cursor ->
            assertEquals("only the other deck's card is left", 1, cursor.count)
            assertTrue(cursor.moveToFirst())
            assertEquals("menjar", cursor.getString(0))
        }
    }

    /** Cards gain a picture credit, and every card already there keeps everything. */
    @Test
    fun migrate15To16_addsImageCreditAndLeavesCardsAlone() {
        helper.createDatabase(TEST_DB, 15).use { db ->
            db.execSQL("INSERT INTO flashcard_decks (id, name, createdAt) VALUES (1, 'Menjar', 1)")
            db.execSQL(
                """
                INSERT INTO flashcards
                    (id, deckId, catalan, romanian, ipa, ipaApproximate, imagePath, createdAt,
                     box, dueAt, reviewCount, lastReviewedAt,
                     reverseBox, reverseDueAt, reverseReviewCount, reverseLastReviewedAt)
                VALUES (1, 1, 'pa', 'pâine', 'ˈpa', 0, 'flashcards/pa.jpg', 5,
                        3, 900, 7, 800, 1, 950, 2, NULL)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 16, true, MIGRATION_15_16)

        db.query(
            "SELECT catalan, imagePath, box, dueAt, reverseBox, imageCredit FROM flashcards",
        ).use { cursor ->
            assertTrue("card survived", cursor.moveToFirst())
            assertEquals("pa", cursor.getString(0))
            assertEquals("its picture survived", "flashcards/pa.jpg", cursor.getString(1))
            assertEquals("and its schedule", 3, cursor.getInt(2))
            assertEquals(900L, cursor.getLong(3))
            assertEquals(1, cursor.getInt(4))
            assertTrue("a picture from before has nobody to credit", cursor.isNull(5))
        }
    }

    /** Decks can be pinned and pictured, cards gain English, and nothing moves. */
    @Test
    fun migrate16To17_addsPinsCoversAndEnglishAndKeepsEverything() {
        helper.createDatabase(TEST_DB, 16).use { db ->
            db.execSQL("INSERT INTO flashcard_decks (id, name, createdAt) VALUES (1, 'Menjar', 1)")
            db.execSQL(
                """
                INSERT INTO flashcards
                    (id, deckId, catalan, romanian, ipa, ipaApproximate, imagePath, imageCredit,
                     createdAt, box, dueAt, reviewCount, lastReviewedAt,
                     reverseBox, reverseDueAt, reverseReviewCount, reverseLastReviewedAt)
                VALUES (1, 1, 'pa', 'pâine', 'ˈpa', 0, 'flashcards/pa.jpg', 'ARASAAC', 5,
                        3, 900, 7, 800, 1, 950, 2, NULL)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 17, true, MIGRATION_16_17)

        db.query("SELECT name, isPinned, coverPath, coverCredit FROM flashcard_decks").use { cursor ->
            assertTrue("deck survived", cursor.moveToFirst())
            assertEquals("Menjar", cursor.getString(0))
            assertEquals("no deck starts pinned", 0, cursor.getInt(1))
            assertTrue("and none has a chosen picture", cursor.isNull(2))
            assertTrue(cursor.isNull(3))
        }
        db.query(
            "SELECT catalan, romanian, imageCredit, box, reverseDueAt, english FROM flashcards",
        ).use { cursor ->
            assertTrue("card survived", cursor.moveToFirst())
            assertEquals("pa", cursor.getString(0))
            assertEquals("pâine", cursor.getString(1))
            assertEquals("its credit survived", "ARASAAC", cursor.getString(2))
            assertEquals("and its schedule", 3, cursor.getInt(3))
            assertEquals(950L, cursor.getLong(4))
            assertTrue("no English was invented", cursor.isNull(5))
        }
    }

    /**
     * Collections arrive, every deck starts on none of them, and — the thing
     * that matters most here — every card is still there.
     *
     * The column carries a foreign key, and the obvious way to add one of those
     * is to rebuild the table; rebuilding `flashcard_decks` means dropping it,
     * and every card in the database hangs off it by `ON DELETE CASCADE`. This
     * test would be the thing that caught that, so it counts the cards.
     */
    @Test
    fun migrate17To18_addsCollectionsAndKeepsEveryCard() {
        helper.createDatabase(TEST_DB, 17).use { db ->
            db.execSQL(
                "INSERT INTO flashcard_decks (id, name, createdAt, isPinned, coverPath) " +
                    "VALUES (1, 'Verdures', 1, 1, 'flashcards/v.jpg')",
            )
            db.execSQL(
                """
                INSERT INTO flashcards
                    (id, deckId, catalan, romanian, english, ipa, ipaApproximate, imagePath,
                     imageCredit, createdAt, box, dueAt, reviewCount, lastReviewedAt,
                     reverseBox, reverseDueAt, reverseReviewCount, reverseLastReviewedAt)
                VALUES (1, 1, 'pastanaga', 'morcov', 'carrot', 'pəstəˈnaɣə', 0, NULL,
                        NULL, 5, 3, 900, 7, 800, 1, 950, 2, NULL)
                """.trimIndent(),
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 18, true, MIGRATION_17_18)

        db.query("SELECT name, isPinned, coverPath, collectionId FROM flashcard_decks").use { cursor ->
            assertTrue("deck survived", cursor.moveToFirst())
            assertEquals("Verdures", cursor.getString(0))
            assertEquals("and its pin", 1, cursor.getInt(1))
            assertEquals("and its picture", "flashcards/v.jpg", cursor.getString(2))
            assertTrue("no deck starts on a collection", cursor.isNull(3))
        }
        db.query("SELECT catalan, romanian, english, box FROM flashcards").use { cursor ->
            assertEquals("the card was not cascaded away", 1, cursor.count)
            assertTrue(cursor.moveToFirst())
            assertEquals("pastanaga", cursor.getString(0))
            assertEquals("morcov", cursor.getString(1))
            assertEquals("carrot", cursor.getString(2))
            assertEquals("and its schedule survived", 3, cursor.getInt(3))
        }
        db.query("SELECT COUNT(*) FROM flashcard_collections").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("the shelf table is there and empty", 0, cursor.getInt(0))
        }
    }

    /**
     * Deleting a collection leaves the decks that were on it alone.
     *
     * The foreign key is added by `ALTER TABLE ADD COLUMN` rather than by
     * rebuilding the table, so that it is really there — and really `SET NULL`
     * rather than `CASCADE` — is worth checking rather than assuming.
     */
    @Test
    fun migrate17To18_deletingACollectionKeepsItsDecks() {
        helper.createDatabase(TEST_DB, 17).use { db ->
            db.execSQL(
                "INSERT INTO flashcard_decks (id, name, createdAt, isPinned) " +
                    "VALUES (1, 'Verdures', 1, 0)",
            )
        }

        helper.runMigrationsAndValidate(TEST_DB, 18, true, MIGRATION_17_18).use { db ->
            db.execSQL("PRAGMA foreign_keys = ON")
            db.execSQL(
                "INSERT INTO flashcard_collections (id, name, createdAt, isPinned) " +
                    "VALUES (9, 'Menjar', 1, 0)",
            )
            db.execSQL("UPDATE flashcard_decks SET collectionId = 9 WHERE id = 1")
            db.execSQL("DELETE FROM flashcard_collections WHERE id = 9")

            db.query("SELECT name, collectionId FROM flashcard_decks").use { cursor ->
                assertTrue("the deck is still here", cursor.moveToFirst())
                assertEquals("Verdures", cursor.getString(0))
                assertTrue("and is simply on no collection now", cursor.isNull(1))
            }
        }
    }

    /** A collection can be given a picture, and none has one to begin with. */
    @Test
    fun migrate18To19_addsCollectionPicturesAndChangesNothingElse() {
        helper.createDatabase(TEST_DB, 18).use { db ->
            db.execSQL(
                "INSERT INTO flashcard_collections (id, name, createdAt, isPinned) " +
                    "VALUES (1, 'Menjar', 5, 1)",
            )
            db.execSQL(
                "INSERT INTO flashcard_decks (id, name, createdAt, isPinned, collectionId) " +
                    "VALUES (2, 'Verdures', 6, 0, 1)",
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 19, true, MIGRATION_18_19)

        db.query(
            "SELECT name, isPinned, coverPath, coverCredit FROM flashcard_collections",
        ).use { cursor ->
            assertTrue("the collection survived", cursor.moveToFirst())
            assertEquals("Menjar", cursor.getString(0))
            assertEquals("and its pin", 1, cursor.getInt(1))
            assertTrue("no collection starts with a picture of its own", cursor.isNull(2))
            assertTrue(cursor.isNull(3))
        }
        db.query("SELECT name, collectionId FROM flashcard_decks").use { cursor ->
            assertTrue("and so did the deck on it", cursor.moveToFirst())
            assertEquals("Verdures", cursor.getString(0))
            assertEquals(1, cursor.getInt(1))
        }
    }

    /** Every step in order, which is what an old install actually runs. */
    @Test
    fun migrate1To19_runsEveryStepInSequence() {
        helper.createDatabase(TEST_DB, 1).use { db ->
            db.execSQL("INSERT INTO folders (id, name, createdAt) VALUES (1, 'Vell', 100)")
        }

        val db = helper.runMigrationsAndValidate(
            TEST_DB,
            19,
            true,
            MIGRATION_1_2,
            MIGRATION_2_3,
            MIGRATION_3_4,
            MIGRATION_4_5,
            MIGRATION_5_6,
            MIGRATION_6_7,
            MIGRATION_7_8,
            MIGRATION_8_9,
            MIGRATION_9_10,
            MIGRATION_10_11,
            MIGRATION_11_12,
            MIGRATION_12_13,
            MIGRATION_13_14,
            MIGRATION_14_15,
            MIGRATION_15_16,
            MIGRATION_16_17,
            MIGRATION_17_18,
            MIGRATION_18_19,
        )

        db.query("SELECT name FROM folders").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("Vell", cursor.getString(0))
        }
        db.query(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name LIKE 'exam%'",
        ).use { cursor ->
            assertEquals("exams came and went", 0, cursor.count)
        }
    }
}
